name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run test:prod

  publish-npm-and-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
          scope: '@tykntech'
      - name: 'Update package version'
      - run: |
          git config user.name "Actions User"
          git config user.email noreply@github.com
          npm version 1.0.$(date +%s)
      - run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@tykntech"
          npm config list
          npm ci
          npm publish --access public --registry https://registry.npmjs.org
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: actions/setup-node@master
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
          scope: '@tykntech'
      - name: 'Publish to GPR'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
